"""train_distilBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nw7MVwSYSLTW2IqvTy5sk1b5KniWplFm

'''
train_distilbert_memo.py
========================
Fine-tunes DistilBERT on the synthetic memo_dataset.csv.

Outputs
-------
  ./memo_model/          — saved model + tokenizer (load with pipeline())
  memo_metrics.json      — eval metrics logged by MLflow
  mlruns/                — MLflow experiment tracking folder

Requirements
------------
  pip install transformers datasets scikit-learn mlflow torch

Run
---
  # On Kaggle/Colab (GPU):
  python train_distilbert_memo.py

  # On Codespaces (CPU, quick smoke test):
  python train_distilbert_memo.py --epochs 1 --max_samples 5000
'''
"""

import argparse
import json
import os

import mlflow
import numpy as np
import pandas as pd
from datasets import Dataset
from sklearn.metrics import (
    average_precision_score,
    classification_report,
    precision_recall_curve,
)
from sklearn.model_selection import train_test_split
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
)

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────────────────────
MODEL_NAME = "distilbert-base-uncased"
MAX_LENGTH = 64  # memo texts are short; 64 tokens is plenty
LABEL_NAMES = ["legitimate", "illicit"]

# ─────────────────────────────────────────────────────────────────────────────
# LOAD & PREPROCESS
# ─────────────────────────────────────────────────────────────────────────────


def load_data(csv_path: str, max_samples: int | None = None) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    df["memo_text"] = df["memo_text"].fillna("").astype(str)

    # Blank memos → placeholder token (model learns to ignore this)
    df["memo_text"] = df["memo_text"].replace("", "[NO_MEMO]")

    if max_samples:
        df = df.sample(n=min(max_samples, len(df)), random_state=42)

    print(
        f"Loaded {len(df):,} rows  |  "
        f"illicit: {df['is_illicit'].sum():,} ({df['is_illicit'].mean()*100:.1f}%)"
    )
    return df


def tokenize(batch, tokenizer):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH,
    )


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    probs = 1 / (1 + np.exp(-logits[:, 1]))
    preds = (probs >= 0.5).astype(int)

    auc_pr = average_precision_score(labels, probs)

    precision, recall, thresholds = precision_recall_curve(labels, probs)
    idx = np.searchsorted(recall[::-1], 0.8)
    prec_at_r80 = float(precision[::-1][idx]) if idx < len(precision) else 0.0

    report = classification_report(labels, preds, output_dict=True, zero_division=0)

    return {
        "auc_pr": round(auc_pr, 4),
        "prec_at_recall_80": round(prec_at_r80, 4),
        "f1_illicit": round(report.get("1", {}).get("f1-score", 0), 4),
        "precision_illicit": round(report.get("1", {}).get("precision", 0), 4),
        "recall_illicit": round(report.get("1", {}).get("recall", 0), 4),
        "accuracy": round(report.get("accuracy", 0), 4),
    }


# ─────────────────────────────────────────────────────────────────────────────
# TRAINING
# ─────────────────────────────────────────────────────────────────────────────


def train(csv_path: str, epochs: int, output_dir: str, max_samples: int):
    # ── Data ──────────────────────────────────────────────────────────────────
    df = load_data(csv_path, max_samples)

    train_df, eval_df = train_test_split(
        df, test_size=0.15, stratify=df["is_illicit"], random_state=42
    )
    print(f"Train: {len(train_df):,}  |  Eval: {len(eval_df):,}")

    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    def to_hf_dataset(df_split):
        return Dataset.from_dict(
            {
                "text": df_split["memo_text"].tolist(),
                "label": df_split["is_illicit"].tolist(),
            }
        ).map(lambda b: tokenize(b, tokenizer), batched=True)

    train_ds = to_hf_dataset(train_df)
    eval_ds = to_hf_dataset(eval_df)

    # ── Model ─────────────────────────────────────────────────────────────────
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

    # ── Class weights (handle 2% illicit imbalance) ───────────────────────────
    # We pass class_weight via a custom Trainer subclass below

    pos_weight = (len(train_df) - train_df["is_illicit"].sum()) / train_df[
        "is_illicit"
    ].sum()
    print(f"Positive class weight: {pos_weight:.1f}x")

    # ── Training args ─────────────────────────────────────────────────────────
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=32,
        per_device_eval_batch_size=64,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="auc_pr",
        greater_is_better=True,
        learning_rate=2e-5,
        weight_decay=0.01,
        warmup_ratio=0.1,
        logging_steps=50,
        fp16=False,  # set True on GPU for ~2x speedup
        report_to="none",
        seed=42,
    )

    # ── MLflow tracking ───────────────────────────────────────────────────────
    mlflow.set_experiment("aml_distilbert_memo")

    with mlflow.start_run(run_name=f"distilbert_ep{epochs}"):
        mlflow.log_params(
            {
                "model": MODEL_NAME,
                "epochs": epochs,
                "max_length": MAX_LENGTH,
                "train_rows": len(train_df),
                "eval_rows": len(eval_df),
                "pos_weight": round(pos_weight, 2),
                "batch_size": training_args.per_device_train_batch_size,
                "lr": training_args.learning_rate,
            }
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_ds,
            eval_dataset=eval_ds,
            processing_class=tokenizer,
            compute_metrics=compute_metrics,
        )

        trainer.train()

        # ── Evaluate & log ─────────────────────────────────────────────────────
        eval_results = trainer.evaluate()
        print("\nFinal eval results:")
        for k, v in eval_results.items():
            if not k.startswith("eval_runtime"):
                print(f"  {k}: {v}")

        mlflow.log_metrics(
            {
                k.replace("eval_", ""): v
                for k, v in eval_results.items()
                if isinstance(v, (int | float))
            }
        )

        # ── Save model ────────────────────────────────────────────────────────
        model_save_path = os.path.join(output_dir, "memo_model")
        trainer.save_model(model_save_path)
        tokenizer.save_pretrained(model_save_path)
        print(f"\nModel saved to: {model_save_path}")

        # ── Save metrics JSON (for DVC/CI eval gate) ──────────────────────────
        metrics = {
            k: v
            for k, v in eval_results.items()
            if isinstance(v, float) and not k.startswith("eval_runtime")
        }
        with open("memo_metrics.json", "w") as f:
            json.dump(metrics, f, indent=2)
        print("Metrics saved to: memo_metrics.json")

        mlflow.log_artifact("memo_metrics.json")
        mlflow.log_artifact(model_save_path)

    return eval_results


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="Fine-tune DistilBERT on AML synthetic memo text."
    )
    parser.add_argument(
        "--csv", type=str, default="memo_dataset.csv", help="Path to memo_dataset.csv"
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=3,
        help="Training epochs (default: 3; use 1 for CPU smoke test)",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./checkpoints",
        help="Directory for model checkpoints",
    )
    parser.add_argument(
        "--max_samples",
        type=int,
        default=None,
        help="Cap dataset size (useful for CPU smoke tests, e.g. 5000)",
    )
    args = parser.parse_known_args()[0]

    os.makedirs(args.output_dir, exist_ok=True)
    train(args.csv, args.epochs, args.output_dir, args.max_samples)


if __name__ == "__main__":
    main()
