name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git push https://neha-at:${HF_TOKEN}@huggingface.co/spaces/neha-at/aml-multimodal-scorer main --force
